services:
  geohunter:
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
  postgres:
    image: postgres:17.5
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}