name: dev

on:
  push:
    branches:
      - 'dev'

defaults:
  run:
    shell: bash
    working-directory: .

env:
  SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  deploy_dev:
    name: Deploy dev environment.
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Script permissions
        run: chmod +x deploy.sh

      - name: Deploy
        run: |
          echo $SECRET;