name: dev

on:
  push:
    branches:
      - 'dev'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy_dev:
    name: Deploy dev environment.
    runs-on: ubuntu-22.04
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Script permissions setup
        run: chmod +x deploy.sh

      - name: Cloning ssh key
        env:
          KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo $KEY >> key
          chmod +r key

      - name: Updating known_hosts
        env:
          HOST: ${{ secrets.SSH_REMOTE_ADDR }}
        run: |
          touch /github/home/.ssh/known_hosts
          ssh-keyscan -H $HOST >> /github/home/.ssh/known_hosts

      - name: Connect to remote & deploy
        env:
          USER: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.SSH_REMOTE_ADDR }}
        run: ./deploy.sh

      - name: Remove key file
        run: |
          rm key