name: dev

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy_dev:
    name: Deploy dev environment.
    runs-on: ubuntu-22.04
    steps:
      -
        name: Deploy.
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_REMOTE_ADDR: ${{ secrets.SSH_REMOTE_ADDR }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          
          ssh -o StrictHostKeyChecking=no -i key $SSH_USER@$SSH_REMOTE_ADDR <<EOF
            
            ls;
          EOF
          
          rm -f key