name: dev

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy_dev:
    name: Deploy dev environment.
    runs-on: ubuntu-22.04
    steps:
      -
        name: Deploy.
        env:
          KEY: ${{ secrets.SSH_KEY }}
          REMOTE_ADDR: ${{ secrets.SSH_REMOTE_ADDR }}
          USER: ${{ secrets.SSH_USER }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_REMOTE_ADDR }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo REMOTE_ADDR;
            echo $USER;