name: dev

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy_dev:
    name: Deploy dev environment.
    runs-on: ubuntu-22.04
    steps:
      -
        name: Connecting to dev stand.
        env:
          TEST_VARIABLE: ${{ vars.TEST_VARIABLE }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo $TEST_VARIABLE
          echo $TEST_SECRET